apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deploy
  namespace: todoapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: ikulyk404/todoapp:3.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY
        volumeMounts:                     # не обов'язкове. Монтує том до контейнера
            - name: todoapp-pv             # ім'я тому (має співпадати з іменем у volumes)
              mountPath: /app/data  # шлях у контейнері, куди буде змонтовано том
            - name: config-volume
              mountPath: /app/configs
              readOnly: true
            - name: secret-volume
              mountPath: /app/secrets
              readOnly: true
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:                              # не обов'язкове. Оголошення томів для пода
        - name: todoapp-pv                 # ім'я тому (використовується у volumeMounts)
          persistentVolumeClaim:           # використовує існуючий PVC
            claimName: pvc-data               # ім'я PVC, який має бути створений окремо
        - name: config-volume
          configMap:
            name: app-config
        - name: secret-volume
          secret:
            secretName: app-secret

